SET ECHO ON
#---------------TEST 사용자 생성---------------#
CREATE USER TEST IDENTIFIED BY 'TEST';

DESC DBA_USERS;

SELECT USERNAME FROM DBA_USERS WHERE USERNAME='TEST';

SELECT * FROM DBA_ROLES;
#---------------TEST 사용자에 권한 부여---------------#
GRANT RESOURCE TO TEST;

SELECT GRANTEE, PRIVILEGE FROM DBA_SYS_PRIVS WHERE GRANTEE='RESOURCE';
#---------------SYSTEM, ROLE 권한---------------#
DESC DBA_SYS_PRIVS

DESC DBA_ROLE_PRIVS
#---------------TABLE COLUMN, LINESIZE 변경후 조회--------------#
COL GRANTEE FOR A30
COL GRANTEE_ROLE FOR A30
COL ADMIN_OPTION FOR A30
COL DEFAULT_ROLE FOR A30
SET LINESIZE 1000
SELECT * FROM DBA_ROLE_PRIVS WHERE GRANTEE='TEST';
