SET ECHO ON
#---------------SYS 사용자로 접속하여 tbl이 다른 사용자에게 준 권한 확인---------------#
CONN SYS/TIBERO

DESC DBA_TAB_PRIVS

SET LINES 200
COL GRANTEE FOR A20
COL OWNER FOR A20
COL TABLE_NAME FOR A20
COL GRANTOR FOR A20
COL PRIVILEGE FOR A20
COL GRANTABLE FOR A20

SELECT * FROM DBA_TAB_PRIVS WHERE OWNER='TEST1' AND TABLE_NAME='TBL';
#---------------TEST2에게 tbl 조회 권한 부여 후 확인---------------#
GRANT SELECT ON TEST1.TBL TO TEST2;
SELECT * FROM DBA_TAB_PRIVS WHERE OWNER='TEST1' AND TABLE_NAME='TBL';

