SET ECHO ON
#SESSION 1#
#---------------TEST1,TEST2 사용자 생성 및 권한 부여---------------#
CREATE USER TEST1 IDENTIFIED BY TEST1;
GRANT CONNECT, RESOURCE TO TEST1;

CREATE USER TEST2 IDENTIFIED BY TEST2;
GRANT CONNECT, RESOURCE TO TEST2;
#---------------TEST1 사용자로 접속후 RXTEST TABLE 생성---------------#
CONN TEST1/TEST1

CREATE TABLE TEST1.RXTEST(ID NUMBER, NAME VARCHAR(20));

INSERT INTO TEST1.RXTEST VALUES(1,'TEST');

COMMIT;

SELECT * FROM TEST1.RXTEST;
#---------------TEST2에게 RXTEST UPDATE 권한 부여---------------#
GRANT UPDATE ON RXTEST TO TEST2;
#---------------현재 시간 확인---------------#
ALTER SESSION SET
NLS_DATE_FORMAT='YYYY/MM/DD
HH24:MI:SS';

SELECT SYSDATE FROM DUAL;
#---------------RXTEST TABLE의 DATA UPDATE(COMMIT X)---------------#
UPDATE TEST1.RXTEST SET NAME ='TESTTEST' WHERE ID =1;

SELECT * FROM TEST1.RXTEST;

