SET ECHO ON
#SESSION 1#
#---------------TEST1,TEST2 사용자 생성 및 권한 부여---------------#
CREATE USER TEST1 IDENTIFIED BY TEST1;
GRANT CONNECT, RESOURCE TO TEST1;

CREATE USER TEST2 IDENTIFIED BY TEST2;
GRANT CONNECT, RESOURCE TO TEST2;
#---------------TEST1로 접속 후 MVCTEST TABLE 생성---------------#
CONN TEST1/TEST1

CREATE TABLE TEST1.MVCTEST(ID NUMBER, NAME VARCHAR(20));

INSERT INTO TEST1.MVCTEST VALUES(1,'TEST');

COMMIT;

SELECT * FROM TEST1.MVCTEST;
#---------------TEST2에게 MVTEST 조회할 권한 부여---------------#
GRANT SELECT ON MVCTEST TO TEST2;
#---------------MVTEST TABLE DATA UPDATE---------------#
UPDATE TEST1.MVCTEST SET NAME='TEST123' WHERE ID=1;
#---------------현재 시간 확인---------------#
ALTER SESSION SET NLS_DATE_FORMAT='YYYY/MM/DD HH24:MI:SS';

SELECT SYSDATE FROM DUAL;

SELECT * FROM TEST1.MVCTEST WHERE ID=1;
