SET ECHO ON
#---------------TEST 사용자 생성 및 권한 부여---------------#
CREATE USER TEST IDENTIFIED BY TEST;

GRANT CONNECT, RESOURCE TO TEST;
#--------------USE_RECYCLEBIN(DROP TABLE 복구 PARAMETER) 활성화---------------#
CONN SYS/TIBERO
ALTER SYSTEM SET USE_RECYCLEBIN='Y';
#--------------TEST 사용자에 접속후 FLASHBACK_TEST TABLE 생성---------------#
CONN TEST/TEST

CREATE TABLE FLASHBACK_TEST(C1 NUMBER, C2 NUMBER, C3 NUMBER);
#--------------FOR LOOP 사용해 DATA 입력---------------#
DECLARE
BEGIN
FOR I IN 1..10000 LOOP
INSERT INTO TEST.FLASHBACK_TEST VALUES(I,I,I);
END LOOP;
END;
/

COMMIT;
#----------------FLASHBACK_TEST TABLE의 DATA 건수 조회--------------#
SELECT COUNT(*) FROM FLASHBACK_TEST;
#----------------TABLE DROP---------------#
DROP TABLE TEST.FLASHBACK_TEST;

SELECT COUNT(*) FROM FLASHBACK_TEST;
#----------------USER_RECYCLEBIN의 PARAMETER 확인---------------#
DESC USER_RECYCLEBIN;

COL OBJECT_NAME FOR A20
COL ORIGINAL_NAME FOR A20
COL TS_NAME FOR A20
COL SPACE FOR A20
SELECT * FROM USER_RECYCLEBIN;
#----------------FLASHBACK_TEST TABLE의 DROP전으로 복구---------------#
FLASHBACK TABLE FLASHBACK_TEST TO BEFORE DROP;
#----------------복구 확인---------------#
SELECT COUNT(*) FROM FLASHBACK_TEST;
#---------------USE_RECYCLEBIN 비활성화---------------#
CONN SYS/TIBERO

ALTER SYSTEM SET USE_RECYCLEBIN=N;


