SET ECHO ON
#--------------TEST 사용자 생성 및 권한 부여---------------#
CREATE USER TEST IDENTIFIED BY TEST;
GRANT CONNECT, RESOURCE TO TEST;
#--------------TEST 사용자에 접속---------------#
CONN TEST/TEST
#--------------HASH_PART TABLE과 PARTITION TABLE 생성---------------#
CREATE TABLE TEST.HASH_PART
 (HASH_NO NUMBER,
 HASH_YEAR CHAR(4) NOT NULL,
HASH_MONTH CHAR(2) NOT NULL,
 HASH_DAY CHAR(2) NOT NULL,
 HASH_NAME VARCHAR2(30),
 HASH NUMBER)
PARTITION BY HASH (HASH_NO)
 (PARTITION HASH_PART1 TABLESPACE TEST_PART1,
 PARTITION HASH_PART2 TABLESPACE TEST_PART2,
 PARTITION HASH_PART3 TABLESPACE TEST_PART3,
 PARTITION HASH_PART4 TABLESPACE TEST_PART4);

INSERT INTO TEST.HASH_PART VALUES(1, 2004, 06, 12, 'SCOTT', 2500);
INSERT INTO TEST.HASH_PART VALUES(2, 2005, 06, 17, 'JONES', 4300);
INSERT INTO TEST.HASH_PART VALUES(3, 2005, 12, 12, 'MILLER', 1200);
INSERT INTO TEST.HASH_PART VALUES(4, 2006, 06, 22, 'FORD', 5200);
INSERT INTO TEST.HASH_PART VALUES(5, 2005, 01, 01, 'LION', 2200);
INSERT INTO TEST.HASH_PART VALUES(6, 2006, 12, 22, 'TIGER', 3300);

COMMIT;

SELECT * FROM TEST.HASH_PART;
#----------------HASH PARTITION TABLE은 DROP 지원 X---------------#
ALTER TABLE TEST.HASH_PART DROP PARTITION HASH_PART4;
#----------------PARTITION TABLE RENAME---------------#
ALTER TABLE TEST.HASH_PART RENAME PARTITION HASH_PART4 TO HASH_PART_FOUR;

COL TABLE_NAME FOR A20
COL PARTITION_NAME FOR A20
SELECT TABLE_NAME, PARTITION_NAME FROM USER_TAB_PARTITIONS WHERE TABLE_NAME='HASH_PART';
#---------------PARTITION DATA 이동하기 위한 일반 TABLE 생성---------------#
CREATE TABLE TEST.HASH_PART_EX
 (HASH_NO NUMBER,
 HASH_YEAR CHAR(4) NOT NULL,
 HASH_MONTH CHAR(2) NOT NULL,
 HASH_DAY CHAR(2) NOT NULL,
 HASH_NAME VARCHAR2(30),
 HASH NUMBER)
 TABLESPACE TEST_PART1;

ALTER TABLE TEST.HASH_PART
EXCHANGE PARTITION HASH_PART2
WITH TABLE TEST.HASH_PART_EX;

SELECT COUNT(*) FROM TEST.HASH_PART
PARTITION(HASH_PART2);

SELECT COUNT(*) FROM TEST.HASH_PART_EX;
#--------------PARTITION TABLE TABLESPACE 변경---------------#
ALTER TABLE TEST.HASH_PART MOVE PARTITION HASH_PART3
TABLESPACE TEST_PART4;

SELECT COUNT(*) FROM TEST.HASH_PART
PARTITION(HASH_PART_FOUR);
#---------------PARTITION TABLE TRUNCATE---------------#
ALTER TABLE TEST.HASH_PART TRUNCATE PARTITION HASH_PART_FOUR;

SELECT COUNT(*) FROM TEST.HASH_PART PARTITION(HASH_PART_FOUR);

