SET ECHO ON
#-------------- 사용자 생성 및 권한 부여---------------#
CREATE USER TEST IDENTIFIED BY TEST;
GRANT CONNECT, RESOURCE TO TEST;
#--------------TEST 사용자에 접속---------------#
CONN TEST/TEST
#---------------LIST_PART TABLE, PARTITON TABLE---------------#
CREATE TABLE TEST.LIST_PART
(LIST_NO NUMBER NOT NULL,
LIST_NAME VARCHAR2(10),
LIST_JOB VARCHAR2(9),
LIST_MGR NUMBER(4),
LIST_HIREDATE DATE,
LIST_SAL NUMBER(7, 2),
LIST_COMM NUMBER(7, 2),
LIST_DEPTNO NUMBER(2))
PARTITION BY LIST (LIST_JOB)
(PARTITION LIST_PART1 VALUES ('MANAGER') TABLESPACE TEST_PART1,
PARTITION LIST_PART2 VALUES ('SALESMAN') TABLESPACE TEST_PART2,
PARTITION LIST_PART3 VALUES ('ANALYST') TABLESPACE TEST_PART3,
PARTITION LIST_PART4 VALUES ('PRESIDENT', 'CLERK') TABLESPACE TEST_PART4);
#---------------LIST_PART_TABLE에 데이터 입력---------------#
INSERT INTO LIST_PART VALUES(1, 'SMITH', 'CLERK', 7902, SYSDATE, 800, NULL, 20); 
INSERT INTO LIST_PART VALUES(2, 'ALLEN', 'SALESMAN', 7698, SYSDATE, 1600, 300, 30); 
INSERT INTO LIST_PART VALUES(3, 'WARD', 'SALESMAN', 7698, SYSDATE, 1250, 500, 30);
INSERT INTO LIST_PART VALUES(4, 'JONES', 'MANAGER', 7839, SYSDATE, 2975, NULL, 20); 
INSERT INTO LIST_PART VALUES(5, 'MARTIN', 'SALESMAN', 7698, SYSDATE, 1250, 1400, 30);
INSERT INTO LIST_PART VALUES(6, 'BLAKE', 'MANAGER', 7839, SYSDATE, 2850, NULL, 30);
INSERT INTO LIST_PART VALUES(7, 'CLARK', 'MANAGER', 7839, SYSDATE, 2450, NULL, 10);  
INSERT INTO LIST_PART VALUES(8, 'SCOTT', 'ANALYST', 7566, SYSDATE, 3000, NULL, 20);
INSERT INTO LIST_PART VALUES(9, 'KING', 'PRESIDENT', NULL, SYSDATE, 5000, NULL, 10); 
INSERT INTO LIST_PART VALUES(10, 'TURNER', 'SALESMAN', 7698,SYSDATE, 1500, 0, 30);
INSERT INTO LIST_PART VALUES(11, 'ADAMS', 'CLERK', 7788,SYSDATE,1100,NULL,20);
INSERT INTO LIST_PART VALUES(12, 'JAMES', 'CLERK', 7698, SYSDATE, 950, NULL, 30);
INSERT INTO LIST_PART VALUES(13, 'FORD', 'ANALYST', 7566, SYSDATE, 3000, NULL, 20);   
INSERT INTO LIST_PART VALUES(14, 'MILLER', 'CLERK', 7782, SYSDATE, 1300, NULL, 10);  

COMMIT;
#---------------PARTITION_TABLE의 LIST_NO조회---------------#
SELECT LIST_NO FROM LIST_PART PARTITION(LIST_PART1);
SELECT LIST_NO FROM LIST_PART PARTITION(LIST_PART2);
SELECT LIST_NO FROM LIST_PART PARTITION(LIST_PART3);
SELECT LIST_NO FROM LIST_PART PARTITION(LIST_PART4);
#---------------새로운 PARTITION_TABLE 생성---------------#
ALTER TABLE LIST_PART
ADD PARTITION LIST_PART_MAX VALUES('DUMMY')
TABLESPACE TEST_PART_MAX;

COL TABLE_NAME FOR A20
COL PARTITION_NAME FOR A20
SELECT TABLE_NAME, PARTITION_NAME FROM USER_TAB_PARTITIONS WHERE TABLE_NAME='LIST_PART';
#---------------PARTITION TABLE DROP---------------#
ALTER TABLE LIST_PART
DROP PARTITION LIST_PART_MAX;
#---------------PARTITION TABLE RENAME---------------#
ALTER TABLE TEST.LIST_PART
RENAME PARTITION LIST_PART4 TO LIST_PART_FOUR;
#---------------일반 TABLE 생성---------------#
CREATE TABLE TEST.LIST_PART_EX
 (LIST_NO NUMBER NOT NULL,
 LIST_NAME VARCHAR2(10),
 LIST_JOB VARCHAR2(9),
 LIST_MGR NUMBER(4),
 LIST_HIREDATE DATE,
 LIST_SAL NUMBER(7, 2),
 LIST_COMM NUMBER(7, 2),
 LIST_DEPTNO NUMBER(2));
#---------------LIST_PART3 PARTITION TABLE 건수 조회---------------#
SELECT COUNT(*) FROM TEST.LIST_PART PARTITION(LIST_PART3);
#---------------LIST_PART3 PARTITION DATA LIST_PART_EX TABLE로 이동---------------#
ALTER TABLE TEST.LIST_PART
EXCHANGE PARTITION LIST_PART3
WITH TABLE TEST.LIST_PART_EX;

SELECT COUNT(*) FROM TEST.LIST_PART PARTITION(LIST_PART3);

SELECT COUNT(*) FROM TEST.LIST_PART_EX;
#---------------LIST_PART1의 TABLESPACE 이동---------------#
ALTER TABLE TEST.LIST_PART
MOVE PARTITION LIST_PART1 TABLESPACE TEST_PART2; 
SELECT COUNT(*) FROM TEST.LIST_PART PARTITION(LIST_PART2); 
#---------------LIST_PART2 PARTITION DATA TRUNCATE---------------#
ALTER TABLE TEST.LIST_PART TRUNCATE PARTITION LIST_PART2;
SELECT COUNT(*) FROM TEST.LIST_PART PARTITION(LIST_PART2);   
